# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/taras/NetBeansProjects/topo-topo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/taras/NetBeansProjects/topo-topo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/taras/NetBeansProjects/topo-topo/CMakeFiles /home/taras/NetBeansProjects/topo-topo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/taras/NetBeansProjects/topo-topo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named topo-topo

# Build rule for target.
topo-topo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 topo-topo
.PHONY : topo-topo

# fast build rule for target.
topo-topo/fast:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/build
.PHONY : topo-topo/fast

CameraState.o: CameraState.cpp.o
.PHONY : CameraState.o

# target to build an object file
CameraState.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/CameraState.cpp.o
.PHONY : CameraState.cpp.o

CameraState.i: CameraState.cpp.i
.PHONY : CameraState.i

# target to preprocess a source file
CameraState.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/CameraState.cpp.i
.PHONY : CameraState.cpp.i

CameraState.s: CameraState.cpp.s
.PHONY : CameraState.s

# target to generate assembly for a file
CameraState.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/CameraState.cpp.s
.PHONY : CameraState.cpp.s

Cylinder.o: Cylinder.cpp.o
.PHONY : Cylinder.o

# target to build an object file
Cylinder.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Cylinder.cpp.o
.PHONY : Cylinder.cpp.o

Cylinder.i: Cylinder.cpp.i
.PHONY : Cylinder.i

# target to preprocess a source file
Cylinder.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Cylinder.cpp.i
.PHONY : Cylinder.cpp.i

Cylinder.s: Cylinder.cpp.s
.PHONY : Cylinder.s

# target to generate assembly for a file
Cylinder.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Cylinder.cpp.s
.PHONY : Cylinder.cpp.s

Geometry.o: Geometry.cpp.o
.PHONY : Geometry.o

# target to build an object file
Geometry.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Geometry.cpp.o
.PHONY : Geometry.cpp.o

Geometry.i: Geometry.cpp.i
.PHONY : Geometry.i

# target to preprocess a source file
Geometry.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Geometry.cpp.i
.PHONY : Geometry.cpp.i

Geometry.s: Geometry.cpp.s
.PHONY : Geometry.s

# target to generate assembly for a file
Geometry.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Geometry.cpp.s
.PHONY : Geometry.cpp.s

MapParser.o: MapParser.cpp.o
.PHONY : MapParser.o

# target to build an object file
MapParser.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/MapParser.cpp.o
.PHONY : MapParser.cpp.o

MapParser.i: MapParser.cpp.i
.PHONY : MapParser.i

# target to preprocess a source file
MapParser.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/MapParser.cpp.i
.PHONY : MapParser.cpp.i

MapParser.s: MapParser.cpp.s
.PHONY : MapParser.s

# target to generate assembly for a file
MapParser.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/MapParser.cpp.s
.PHONY : MapParser.cpp.s

Object.o: Object.cpp.o
.PHONY : Object.o

# target to build an object file
Object.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Object.cpp.o
.PHONY : Object.cpp.o

Object.i: Object.cpp.i
.PHONY : Object.i

# target to preprocess a source file
Object.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Object.cpp.i
.PHONY : Object.cpp.i

Object.s: Object.cpp.s
.PHONY : Object.s

# target to generate assembly for a file
Object.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Object.cpp.s
.PHONY : Object.cpp.s

OpenGlRenderer.o: OpenGlRenderer.cpp.o
.PHONY : OpenGlRenderer.o

# target to build an object file
OpenGlRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/OpenGlRenderer.cpp.o
.PHONY : OpenGlRenderer.cpp.o

OpenGlRenderer.i: OpenGlRenderer.cpp.i
.PHONY : OpenGlRenderer.i

# target to preprocess a source file
OpenGlRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/OpenGlRenderer.cpp.i
.PHONY : OpenGlRenderer.cpp.i

OpenGlRenderer.s: OpenGlRenderer.cpp.s
.PHONY : OpenGlRenderer.s

# target to generate assembly for a file
OpenGlRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/OpenGlRenderer.cpp.s
.PHONY : OpenGlRenderer.cpp.s

Renderer.o: Renderer.cpp.o
.PHONY : Renderer.o

# target to build an object file
Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Renderer.cpp.o
.PHONY : Renderer.cpp.o

Renderer.i: Renderer.cpp.i
.PHONY : Renderer.i

# target to preprocess a source file
Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Renderer.cpp.i
.PHONY : Renderer.cpp.i

Renderer.s: Renderer.cpp.s
.PHONY : Renderer.s

# target to generate assembly for a file
Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Renderer.cpp.s
.PHONY : Renderer.cpp.s

Scene.o: Scene.cpp.o
.PHONY : Scene.o

# target to build an object file
Scene.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Scene.cpp.o
.PHONY : Scene.cpp.o

Scene.i: Scene.cpp.i
.PHONY : Scene.i

# target to preprocess a source file
Scene.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Scene.cpp.i
.PHONY : Scene.cpp.i

Scene.s: Scene.cpp.s
.PHONY : Scene.s

# target to generate assembly for a file
Scene.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Scene.cpp.s
.PHONY : Scene.cpp.s

SceneFactory.o: SceneFactory.cpp.o
.PHONY : SceneFactory.o

# target to build an object file
SceneFactory.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/SceneFactory.cpp.o
.PHONY : SceneFactory.cpp.o

SceneFactory.i: SceneFactory.cpp.i
.PHONY : SceneFactory.i

# target to preprocess a source file
SceneFactory.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/SceneFactory.cpp.i
.PHONY : SceneFactory.cpp.i

SceneFactory.s: SceneFactory.cpp.s
.PHONY : SceneFactory.s

# target to generate assembly for a file
SceneFactory.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/SceneFactory.cpp.s
.PHONY : SceneFactory.cpp.s

Sphere.o: Sphere.cpp.o
.PHONY : Sphere.o

# target to build an object file
Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Sphere.cpp.o
.PHONY : Sphere.cpp.o

Sphere.i: Sphere.cpp.i
.PHONY : Sphere.i

# target to preprocess a source file
Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Sphere.cpp.i
.PHONY : Sphere.cpp.i

Sphere.s: Sphere.cpp.s
.PHONY : Sphere.s

# target to generate assembly for a file
Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/Sphere.cpp.s
.PHONY : Sphere.cpp.s

TopoView.o: TopoView.cpp.o
.PHONY : TopoView.o

# target to build an object file
TopoView.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/TopoView.cpp.o
.PHONY : TopoView.cpp.o

TopoView.i: TopoView.cpp.i
.PHONY : TopoView.i

# target to preprocess a source file
TopoView.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/TopoView.cpp.i
.PHONY : TopoView.cpp.i

TopoView.s: TopoView.cpp.s
.PHONY : TopoView.s

# target to generate assembly for a file
TopoView.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/TopoView.cpp.s
.PHONY : TopoView.cpp.s

TriangleStorageImpl.o: TriangleStorageImpl.cpp.o
.PHONY : TriangleStorageImpl.o

# target to build an object file
TriangleStorageImpl.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/TriangleStorageImpl.cpp.o
.PHONY : TriangleStorageImpl.cpp.o

TriangleStorageImpl.i: TriangleStorageImpl.cpp.i
.PHONY : TriangleStorageImpl.i

# target to preprocess a source file
TriangleStorageImpl.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/TriangleStorageImpl.cpp.i
.PHONY : TriangleStorageImpl.cpp.i

TriangleStorageImpl.s: TriangleStorageImpl.cpp.s
.PHONY : TriangleStorageImpl.s

# target to generate assembly for a file
TriangleStorageImpl.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/TriangleStorageImpl.cpp.s
.PHONY : TriangleStorageImpl.cpp.s

View.o: View.cpp.o
.PHONY : View.o

# target to build an object file
View.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/View.cpp.o
.PHONY : View.cpp.o

View.i: View.cpp.i
.PHONY : View.i

# target to preprocess a source file
View.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/View.cpp.i
.PHONY : View.cpp.i

View.s: View.cpp.s
.PHONY : View.s

# target to generate assembly for a file
View.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/View.cpp.s
.PHONY : View.cpp.s

ViewParams.o: ViewParams.cpp.o
.PHONY : ViewParams.o

# target to build an object file
ViewParams.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/ViewParams.cpp.o
.PHONY : ViewParams.cpp.o

ViewParams.i: ViewParams.cpp.i
.PHONY : ViewParams.i

# target to preprocess a source file
ViewParams.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/ViewParams.cpp.i
.PHONY : ViewParams.cpp.i

ViewParams.s: ViewParams.cpp.s
.PHONY : ViewParams.s

# target to generate assembly for a file
ViewParams.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/ViewParams.cpp.s
.PHONY : ViewParams.cpp.s

ViewState.o: ViewState.cpp.o
.PHONY : ViewState.o

# target to build an object file
ViewState.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/ViewState.cpp.o
.PHONY : ViewState.cpp.o

ViewState.i: ViewState.cpp.i
.PHONY : ViewState.i

# target to preprocess a source file
ViewState.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/ViewState.cpp.i
.PHONY : ViewState.cpp.i

ViewState.s: ViewState.cpp.s
.PHONY : ViewState.s

# target to generate assembly for a file
ViewState.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/ViewState.cpp.s
.PHONY : ViewState.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/topo-topo.dir/build.make CMakeFiles/topo-topo.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... topo-topo"
	@echo "... CameraState.o"
	@echo "... CameraState.i"
	@echo "... CameraState.s"
	@echo "... Cylinder.o"
	@echo "... Cylinder.i"
	@echo "... Cylinder.s"
	@echo "... Geometry.o"
	@echo "... Geometry.i"
	@echo "... Geometry.s"
	@echo "... MapParser.o"
	@echo "... MapParser.i"
	@echo "... MapParser.s"
	@echo "... Object.o"
	@echo "... Object.i"
	@echo "... Object.s"
	@echo "... OpenGlRenderer.o"
	@echo "... OpenGlRenderer.i"
	@echo "... OpenGlRenderer.s"
	@echo "... Renderer.o"
	@echo "... Renderer.i"
	@echo "... Renderer.s"
	@echo "... Scene.o"
	@echo "... Scene.i"
	@echo "... Scene.s"
	@echo "... SceneFactory.o"
	@echo "... SceneFactory.i"
	@echo "... SceneFactory.s"
	@echo "... Sphere.o"
	@echo "... Sphere.i"
	@echo "... Sphere.s"
	@echo "... TopoView.o"
	@echo "... TopoView.i"
	@echo "... TopoView.s"
	@echo "... TriangleStorageImpl.o"
	@echo "... TriangleStorageImpl.i"
	@echo "... TriangleStorageImpl.s"
	@echo "... View.o"
	@echo "... View.i"
	@echo "... View.s"
	@echo "... ViewParams.o"
	@echo "... ViewParams.i"
	@echo "... ViewParams.s"
	@echo "... ViewState.o"
	@echo "... ViewState.i"
	@echo "... ViewState.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

